### ISSUE TITLE
`replacement has length zero` in `dnaPT_charts.sh` and `dnaPT_landscape.sh` 

### ISSUE THREAD

**Issue by sigau** [clemgoub/dnaPT_utils#4]
Hi 
I'm running the landscape and charts script and sometime I got a strange error : 
src/dnaPT_utils/dnaPT_landscapes.sh -I /beegfs/project/nega/dnapipe/third_set/Anabas_testudineus/dnapipe_025_Anabas_testudineus/final_dnapipete_output
input dataset:      /beegfs/project/nega/dnapipe/third_set/Anabas_testudineus/dnapipe_025_Anabas_testudineus/final_dnapipete_output
output folder:      /beegfs/project/nega/dnapipe/third_set/Anabas_testudineus/dnapipe_025_Anabas_testudineus/final_dnapipete_output
output prefix:      dnaPipeTE
super-family level: FALSE
custom ylim:        FALSE
plotting Unknown:   TRUE
[1] "load variables..."
Erreur dans col.lands[i] <- cols$V2[grep(pattern = paste("^", levels(as.factor(land$TE_subclass))[i],  : 
  l'argument de remplacement est de longueur nulle
Exécution arrêtée
All done, results in /beegfs/project/nega/dnapipe/third_set/Anabas_testudineus/dnapipe_025_Anabas_testudineus/final_dnapipete_output/

Do you know how I can correct that ? 
Thanks !

Gautier

**Comment by clemgoub** [comment]
Hello!

The first thing to look at if you used the latest version of this repos, I remember fixing a bug related to a similar error. If yes, it may be due to one/some annotations not being recognized: would you be willing to share your ouptut folder with me I can debug locally (my email is in my profile).

Best,

Clément

**Comment by clemgoub** [comment]
I found the issue! 

You had some classification unknown of `dnaPT_utils`:

```
PLE/Chlamys
PLE/Naiad
PLE
DNA/Ginger-1
Retroposon/sno
```

I have now added them to `colors.land` in the `dnaPT_utils` repos. This file has all the accepted classes, and if you encounter the same error again, it is likely that it is because some annotations are missing. I have updated the README with details on how to modify `colors.land` ([here](https://github.com/clemgoub/dnaPT_utils#known-issues))

Best,

Clément
